### ISSUE TITLE
Pro version?

### ISSUE THREAD

**Issue by sqs** [goreleaser/goreleaser-cross#22]
I just subscribed to Pro, and I'd like to use this repo's Docker image to make Pro cross-compiles. But it looks like it only includes `goreleaser` not `goreleaser-pro`.

**Comment by caarlos0** [comment]
Indeed, I'll look into it, thanks @sqs!

**Comment by troian** [comment]
`goreleaser-pro` is now available within `ghcr.io/goreleaser/goreleaser-cross-pro`
