### ISSUE TITLE
OpenSSL removed, breaking builds with private dependencies accessed over SSH 

### ISSUE THREAD

**Issue by fortytw2** [goreleaser/goreleaser-cross#25]
In this commit: https://github.com/goreleaser/goreleaser-cross/commit/a99f03b8de5aea4d628ad7f1aae787087ed8c8e4#diff-8f5e5cdf9d8c402d512a6f0cc8b414617cd93c533d36b90ea46def15909f28afL42

It looks like `openssl` was removed from the `goreleaser/goreleaser-cross` image, which breaks builds with private dependencies with an error like :

```
git ls-remote -q origin 
...
mod info ....
...
ssh -o ControlMaster=no -o BatchMode=yes: 1: ssh: not found
```

I can send a PR to add this back, if you'd like

**Comment by troian** [comment]
thanks for reporting. i'm doing a bit of refactoring, will put it back.

**Comment by troian** [comment]
try latest `v1.9.5` should have fix in it

**Comment by troian** [comment]
feel free to reopen if issue persists
