### ISSUE TITLE
libxar.so not found

### ISSUE THREAD

**Issue by AskAlexSharov** [goreleaser/goreleaser-cross#28]
Version: 1.19.5
```
failed to build for darwin_arm64

/usr/local/go/pkg/tool/linux_amd64/link: running oa64-clang++ failed: exit status 255
[263](https://github.com/ledgerwatch/erigon/actions/runs/4120944114/jobs/7116173623#step:6:264)
/osxcross/bin/arm64-apple-darwin21.1-ld: error while loading shared libraries: libxar.so.1: cannot open shared object file: No such file or directory
[264](https://github.com/ledgerwatch/erigon/actions/runs/4120944114/jobs/7116173623#step:6:265)
clang: error: unable to execute command: No such file or directory
```
https://github.com/ledgerwatch/erigon/actions/runs/4121190447/jobs/7116640008#step:6:75
https://github.com/ledgerwatch/erigon/blob/devel/.goreleaser.yml

**Comment by troian** [comment]
thanks, checking

**Comment by troian** [comment]
retagged `1.19.5`. please retry

**Comment by AskAlexSharov** [comment]
Retry failed: https://github.com/ledgerwatch/erigon/actions/runs/4130391548/jobs/7137027883#step:7:258
```
   error=failed to build for darwin_arm64

/usr/local/go/pkg/tool/linux_amd64/link: running oa64-clang++ failed: exit status 255
[258](https://github.com/ledgerwatch/erigon/actions/runs/4130391548/jobs/7137027883#step:7:259)
/osxcross/bin/arm64-apple-darwin21.1-ld: error while loading shared libraries: libxar.so.1: cannot open shared object file: No such file or directory
```

**Comment by AskAlexSharov** [comment]
yes. this way works. thank you.

**Comment by arbourd** [comment]
I'm still experiencing this in both 1.20 and 1.19.

- `v1.20` is not the same image as `v1.20.0`
- `v1.19` is not the same image as `v1.19.5`

For anyone pulling `v1.20` or `v1.19` are going to get non-working versions of the image.

**Comment by troian** [comment]
you can set LD_LIBRARY_PATH manually

**Comment by arbourd** [comment]
The tags `v1.20` need to be updated to reference `v1.20.0`.

**Comment by troian** [comment]
thanks, i'll update

**Comment by troian** [comment]
i've completely retagged `1.20.x` `1.20`. there was a fail during release.
