### ISSUE TITLE
Docker images version separator changed from - to .

### ISSUE THREAD

**Issue by ilkelma** [goreleaser/goreleaser-cross#30]
Currently our automation that uses the goreleaser-cross docker images is broken because of this change:

https://github.com/goreleaser/goreleaser-cross/commit/903176d911a16582282727f10b358c2f18b795d5#diff-324dcb1f6809c46621bb617852fa831a1b2f98aaa137bb65db03c065c04e1776L29-L30

Which changed the separator between versions from `-` to `.` in the published docker images starting from goreleaser-cross v1.20.0.

I could find no communication regarding this change but I wanted to check if it was in fact an intended change going forward and we should change our automation to match the new format or simply a bug to be fixed (so we should hold off or offer our own MR to fix the issue instead of changing the automation).

**Comment by troian** [comment]
this is a bug, thank you. we will fix it tmr

**Comment by troian** [comment]
retagged 1.20
