### ISSUE TITLE
Question: recommended way to add c libraries in the image

### ISSUE THREAD

**Issue by olup** [goreleaser/goreleaser-cross#5]
I use a `libmp3lame` binding in my project, and I am not sure how to have those available in the docker image. Do I need to recreate an image including those ? Should I just have them in my repo and point the compiler to them ? Can I `apt-get` them from the container ?

**Comment by olup** [comment]
Ok, no worries, I guess I need to be making a sysroot ?

**Comment by troian** [comment]
Yeah, `sysroot` is only the path 😉
