### ISSUE TITLE
How to Build Snaps?

### ISSUE THREAD

**Issue by JonathanHope** [goreleaser/goreleaser-cross#59]
When I try and build a snap with this image I get the following error:
```
error=snapcraft not present in $PATH
```

I looked into installing snapcraft and found the following instructions:
```
sudo apt update
sudo apt install snapd
sudo snap install core
```

I tried to add this to a Dockerfile:
```
FROM goreleaser/goreleaser-cross:v1.21

RUN apt-get update \
 && apt-get install --no-install-recommends -y -q \
    snapd
RUN snap install core
RUN snap install snapcraft --classic
```

But that fails with:
```
error: cannot communicate with server: Post "http://localhost/v2/snaps/core": dial unix /run/snapd.socket: connect: no such file or directory
```

Any ideas on how build snaps with this Docker image?

**Comment by caarlos0** [comment]
unfortunately, afaik, snapd (or snapcraft, dont really remember) don't work inside docker containers... we may need to document this better though

**Comment by JonathanHope** [comment]
No worries. I was able to figure out a workaround by building with Zig on MacOS agents and then using the Snapcraft Docker images to build the snap. Thanks for getting back to me!
