### ISSUE TITLE
v1.22.5 image tag is missing

### ISSUE THREAD

**Issue by rootulp** [goreleaser/goreleaser-cross#79]
## Context

The v1.22.5 image tag is missing from https://github.com/goreleaser/goreleaser-cross/pkgs/container/goreleaser-cross/versions?filters%5Bversion_type%5D=tagged

## Problem

Our repo upgrades Golang versions regularly and it is a maintenance burden to check if the relevant goreleaser-cross image version exists. 

## Proposal

Create a goreleaser-cross image tag for every Go release.

**Comment by troian** [comment]
i'll release it in a next day or two, have to do it manually as gh actions runners always fails due to no space issue.
you can use `v1.22.6` tho

**Comment by rootulp** [comment]
Thanks yea we worked around the issue by bumping to Go 1.22.6 in https://github.com/celestiaorg/celestia-app/pull/3803

**Comment by rootulp** [comment]
We stopped using a deprecated field in https://github.com/celestiaorg/celestia-app/pull/3795 but it looks like goreleaser-cross is still using v1.x of Goreleaser. Are there plans to upgrade to Goreleaser v2.x?

In either case, we'll have to revert that PR, pin to Goreleaser v1.x in our goreleaser-check command, and then cut another release to get pre-build binaries to work.

**Comment by qwqcode** [comment]
golang 1.22.7 has also been released, which fixes security issues

**Comment by troian** [comment]
1.22.7 released

**Comment by caarlos0** [comment]
fwiw this replaced `:latest` as well it seems

**Comment by caarlos0** [comment]
running this to fix:

```
❯ for name in goreleaser-cross-base goreleaser-cross goreleaser-cross-pro
          for registry in ghcr.io docker.io
                  docker pull $registry/goreleaser/$name:v1.23.1
                  docker tag $registry/goreleaser/$name:v1.23.1 $registry/goreleaser/$name:latest
                  docker push $registry/goreleaser/$name:latest
              end
  end
```
