### ISSUE TITLE
Std library functions missing:

### ISSUE THREAD

**Issue by albertobruin** [goreleaser/goreleaser-cross#85]
Hi, First of all thanks for this great project.
I am having trouble getting cross compiling on windows (other os work fine) a go project that requires duckdb which in turns requires cgo enabled.
It seems the project establishes some [ld flags to be used](https://github.com/marcboeker/go-duckdb/blob/main/cgo_static.go#L12C1-L12C111) which didn't really work with `goreleaser-cross`. After a lot of tinkering a got most errors to go away by adding `-lpthread` and chaning `-lRstrtmgr` into `-lrstrtmgr`, but I'm still getting lots of errors related to missing std references such as `undefined reference to `std::__throw_bad_array_new_length()` or `std::condition_variable::notify_one()`
Am I missing a flag or does the cross-compiler image have a different version or std c++ library?

**Comment by troian** [comment]
hey @albertobruin
it does look like it cannot locate library path

I would suggest to add verbose flags to `CGO_LDFLAGS=-Wl,--verbose` and see where the linker is looking for particular lib

for reference see if this helps https://github.com/goreleaser/goreleaser-cross/issues/84

**Comment by albertobruin** [comment]
Thanks a lot for your response @troian. We ended up not using goreleaser-cross and just built on the different OSs natively
